apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T15:26:41Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "8069"
  uid: 1d8b4f7a-9da2-4ecc-83ca-dd8bb847cc6f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.97.209.45
  clusterIPs:
  - 10.97.209.45
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32452
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
